version: "2"

checks:
  method-complexity:
    config:
      threshold: 6    # 5 is *just* too low and flags a number of otherwise readable methods
  method-lines:
    config:
      threshold: 30   # with object literals, lines are not a great measure

exclude_patterns:
  - CHANGELOG.md
  - config/
  - docs/api/
  - docs/dev/style.md
  - src/migration/
  - vendor/

plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 225
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  tslint:
    enabled: true
    config: config/tslint.cc.json
