version: "2"

exclude_patterns:
  - CHANGELOG.md
  - docs/api/
  - docs/dev/style.md
  - src/migration/
  - vendor/

plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 225
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  tslint:
    enabled: true
    config: config/tslint.cc.json
