FROM docker.artifacts.apextoaster.com/library/node:18-alpine

# install jq, sqlite cli
RUN apk add bash curl jq sqlite

# copy build output
COPY package.json yarn.lock /app/
COPY out/vendor.js /app/out/
COPY out/index.js out/main.js /app/out/

WORKDIR /app

# install native modules
RUN yarn install --production

ENTRYPOINT [ "node", "/app/out/index.js" ]
