$schema: "http://json-schema.org/schema#" # yes, this is a json schema written in yaml
$id: "https://github.com/ssube/isolex/schema.yml"
definitions:
  array-mapper:
    type: object
    additionalProperties: false
    properties:
      rest:
        type: string
      skip:
        type: number
      take:
        type: array
        items:
          type: string
 
  checklist:
    type: object
    additionalProperties: false
    properties:
      data:
        type: array
        items:
          type: string
      mode:
        enum: [exclude, include]

  client-github:
    type: object
    additionalProperties: false
    required: [token]
    properties:
      root:
        type: string
      token:
        type: string

  client-gitlab:
    type: object
    additionalProperties: false
    required: [token]
    properties:
      root:
        type: string
      token:
        type: string
 
  entity-command:
    type: object
    additionalProperties: true
    properties:
      noun:
        type: string
      verb:
        type: string

  entity-context-channel:
    type: object
    additionalProperties: false
    required: [id, thread]
    properties:
      id:
        type: string
      thread:
        type: string
 
  entity-context:
    type: object
    additionalProperties: false
    required: [channel, name, uid]
    properties:
      channel:
        $ref: "#/definitions/entity-context-channel"
      name:
        type: string
      target:
        $ref: "#/definitions/service-metadata"
      uid:
        type: string

  entity-message:
    type: object
    additionalProperties: false
    required: [body, type]
    properties:
      body:
        type: string
      type:
        enum: [text/plain]

  match-rule:
    type: object
    additionalProperties: false
    properties:
      key:
        type: string
      negate:
        type: boolean
      operator:
        enum: [any, every]
      values:
        type: array
        items:
          $ref: "#/definitions/match-rule-value"

  match-rule-value:
    type: object
    additionalProperties: false
    oneOf:
      - required: [regexp]
      - required: [string]
    properties:
      regexp:
        regexp: true
      string:
        type: string

  match-data:
    type: object
    additionalProperties: false
    properties:
      rules:
        type: array
        items:
          $ref: "#/definitions/match-rule"

  match-results:
    type: object
    additionalProperties: false
    properties:
      matched:
        type: boolean
    errors:
      type: array
      items:
        type: string

  service-bot:
    type: object
    properties:
      controllers:
        type: array
        items:
          $ref: "#/definitions/service-definition"
      filters:
        type: array
        items:
          $ref: "#/definitions/service-definition"
      listeners:
        type: array
        items:
          $ref: "#/definitions/service-definition"
      logger:
        type: object
        properties:
          level:
            enum: [debug, info, warn, error]
          name:
            type: string
      migrate:
        type: boolean
      parsers:
        type: array
        items:
          $ref: "#/definitions/service-definition"
      storage:
        type: object
        properties:
          database:
            type: string
          type:
            type: string

  service-controller:
    allOf:
      - $ref: "#/definitions/service-data"
      - type: object
        additionalProperties: true
        required: [transforms]
        properties:
          transforms:
            type: array
            items:
              $ref: "#/definitions/service-definition"

  service-controller-completion:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        additionalProperties: true
        required: [defaultTarget]
        properties:
          defaultTarget:
            $ref: "#/definitions/service-metadata"

  service-controller-count:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          default:
            type: object
            additionalProperties: false
            properties:
              count:
                type: string
              name:
                type: string
          field:
            type: object
            additionalProperties: false
            properties:
              count:
                type: string
              name:
                type: string
          range:
            type: object
            additionalProperties: false
            properties:
              min:
                type: number
              max:
                type: number

  service-controller-dice:
    $ref: "#/definitions/service-controller"

  service-controller-echo:
    $ref: "#/definitions/service-controller"

  service-controller-github-pr:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        required: [client]
        properties:
          client:
            $ref: "#/definitions/client-github"

  service-controller-gitlab-ci:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        required: [client]
        properties:
          client:
            $ref: "#/definitions/client-gitlab"

  service-controller-kubernetes:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          context:
            type: object
            additionalProperties: false
            properties:
              cluster:
                type: boolean
              default:
                type: boolean
              path:
                type: string
          default:
            type: object
            additionalProperties: false
            properties:
              namespace:
                type: string

  service-controller-learn:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          field:
            type: string
          nouns:
            $ref: "#/definitions/checklist"

  service-controller-math:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          format:
            type: object
            additionalProperties: false
            properties:
              list:
                type: object
                additionalProperties: false
                properties:
                  join:
                    type: string
              number:
                type: object
                additionalProperties: false
                properties:
                  notation:
                    enum: [fixed, exponential, engineering, auto]
                  precision:
                    type: number
                  lowerExp:
                    type: number
                  upperExp:
                    type: number
                  fraction:
                    type: string
              node:
                type: object
                additionalProperties: false
                properties:
                  implicit:
                    type: string
                  parenthesis:
                    type: string
          math:
            type: object
            additionalProperties: false
            properties:
              matrix:
                type: string
              number:
                type: string

  service-controller-random:
    $ref: "#/definitions/service-controller"

  service-controller-search:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          count:
            type: number
          field:
            type: string
          request:
            type: object
            additionalProperties: false
            properties:
              method:
                type: string
              url:
                type: string
 
  service-controller-sed:
    $ref: "#/definitions/service-controller"

  service-controller-session:
    $ref: "#/definitions/service-controller"

  service-controller-time:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        properties:
          locale:
            type: string
          zone:
            type: string

  service-controller-token:
    $ref: "#/definitions/service-controller"

  service-controller-user:
    $ref: "#/definitions/service-controller"

  service-controller-weather:
    allOf:
      - $ref: "#/definitions/service-controller"
      - type: object
        additionalProperties: true
        required: [api]
        properties:
          api:
            type: object
            additionalProperties: false
            required: [key, root]
            properties:
              key:
                type: string
              root:
                type: string

  service-filter:
    $ref: "#/definitions/service-data"

  service-filter-command:
    $ref: "#/definitions/service-filter-rule"

  service-filter-message:
    $ref: "#/definitions/service-filter-rule"

  service-filter-rule:
     allOf:
      - $ref: "#/definitions/service-filter"
      - type: object
        additionalProperties: true
        required: [match]
        properties:
          match:
            $ref: "#/definitions/match-data"

  service-filter-user:
    allOf:
      - $ref: "#/definitions/service-filter"
      - type: object
        additionalProperties: true
        required: [users]
        properties:
          users:
            $ref: "#/definitions/checklist"

  service-interval:
    allOf:
      - $ref: "#/definitions/service-data"
      - type: object
        additionalProperties: true
        required: [defaultContext, defaultTarget, frequency]
        properties:
          defaultContext:
            $ref: "#/definitions/entity-context"
          defaultTarget:
            $ref: "#/definitions/service-metadata"
          frequency:
            type: object
            additionalProperties: false
            oneOf:
              - required: [cron]
              - required: [zeit]
            properties:
              cron:
                type: string
              zeit:
                type: string
 
  service-interval-command:
    allOf:
      - $ref: "#/definitions/service-interval"
      - type: object
        additionalProperties: true
        required: [defaultCommand]
        properties:
          defaultCommand:
            $ref: "#/definitions/entity-command"
    
  service-interval-event:
    allOf:
      - $ref: "#/definitions/service-interval"
      - type: object
        additionalProperties: true
        required: [services]
        properties:
          services:
            type: array
            items:
              $ref: "#/definitions/service-metadata"

  service-interval-message:
    allOf:
      - $ref: "#/definitions/service-interval"
      - type: object
        additionalProperties: true
        required: [defaultMessage]
        properties:
          defaultMessage:
            $ref: "#/definitions/entity-message"

  service-interval-metrics:
    $ref: "#/definitions/service-interval"

  service-listener:
    $ref: "#/definitions/service-data"
 
  service-listener-discord:
    allOf:
      - $ref: "#/definitions/service-listener"
      - type: object
        additionalProperties: true
        required: [presence, token]
        properties:
          presence:
            type: object
          token:
            type: string

  service-listener-express:
    allOf:
      - $ref: "#/definitions/service-listener"
      - type: object
        additionalProperties: true
        required: [defaultTarget, expose, graph, listen, token]
        properties:
          defaultTarget:
            $ref: "#/definitions/service-metadata"
          expose:
            type: object
            properties:
              graph:
                type: boolean
              graphiql:
                type: boolean
              metrics:
                type: boolean
          graph:
            $ref: "#/definitions/service-definition"
          listen:
            type: object
            properties:
              address:
                type: string
              port:
                type: number
          token:
            type: object
            properties:
              audience:
                type: string
              issuer:
                type: string
              scheme:
                type: string
              secret:
                type: string

  service-listener-slack:
    allOf:
      - $ref: "#/definitions/service-listener"
      - type: object
        additionalProperties: true
        required: [token]
        properties:
          token:
            type: object
            additionalProperties: false
            required: [bot, web]
            properties:
              bot:
                type: string
              web:
                type: string

  service-parser:
    allOf:
      - $ref: "#/definitions/service-data"
      - type: object
        properties:
          defaultCommand:
            $ref: "#/definitions/entity-command"
          preferData:
            type: boolean
          match:
            $ref: "#/definitions/match-data"

  service-parser-args:
    allOf:
      - $ref: "#/definitions/service-parser"
      - type: object
        properties:
          args:
            type: object
            properties:
              array:
                type: array
                items:
                  type: string
              boolean:
                type: array
                items:
                  type: string
              configuration:
                type: object
              count:
                type: array
                items:
                  type: string
              default:
                type: array
                items:
                  type: string
              number:
                type: array
                items:
                  type: string
              required:
                type: array
                items:
                  type: string
              string:
                type: array
                items:
                  type: string
              "--":
                type: boolean

  service-parser-echo:
    allOf:
      - $ref: "#/definitions/service-parser"
      - type: object
        properties:
          dataMapper:
            $ref: "#/definitions/array-mapper"

  service-parser-lex:
    allOf:
      - $ref: "#/definitions/service-parser"
      - type: object
        properties:
          account:
            type: object
            additionalProperties: false
            properties:
              accessKey:
                type: string
              secretKey:
                type: string
          bot:
            type: object
            additionalProperties: false
            properties:
              alias:
                type: string
              name:
                type: string
              region:
                type: string

  service-parser-regex:
    allOf:
      - $ref: "#/definitions/service-parser"
      - type: object
        properties:
          dataMapper:
            $ref: "#/definitions/array-mapper"
          regexp:
            type: string

  service-parser-split:
    allOf:
      - $ref: "#/definitions/service-parser"
      - type: object
        properties:
          dataMapper:
            $ref: "#/definitions/array-mapper"
          every:
            type: boolean
          split:
            type: object
 
  service-parser-yaml:
    $ref: "#/definitions/service-parser"
 
  service-transform:
    $ref: "#/definitions/service-data"

  service-transform-flatten:
    allOf:
      - $ref: "#/definitions/service-transform"
      - type: object
        required: [join, keys]
        properties:
          deep:
            type: boolean
          join:
            type: string
          keys:
            type: array
            items:
              type: string

  service-transform-jsonpath:
    allOf:
      - $ref: "#/definitions/service-transform"
      - type: object
        properties:
          queries:
            type: object
            additionalProperties:
              type: string

  service-transform-template:
    allOf:
      - $ref: "#/definitions/service-transform"
      - type: object
        additionalProperties: true
        required: [templates]
        properties:
          templates:
            type: object
            additionalProperties:
              type: string
 
  service-metadata:
    type: object
    additionalProperties: false
    required: [kind, name]
    properties:
      kind:
        type: string
      name:
        type: string

  service-data:
    type: object
    additionalProperties: true
    properties:
      filters:
        type: array
        items:
          $ref: "#/definitions/service-definition"
      strict:
        type: boolean
        default: true

  service-definition:
    type: object
    additionalProperties: false
    required: [data, metadata]
    properties:
      data:
        $ref: "#/definitions/service-data"
      metadata:
        $ref: "#/definitions/service-metadata"

  service-graph:
    type: object

  utils-cooldown:
    type: object
    additionalProperties: false
    properties:
      base:
        type: number
      grow:
        type: number

# root
type: object
additionalProperties: false
required: [data, metadata]
properties:
  metadata:
    $ref: "#/definitions/service-metadata"
  data:
    $ref: "#/definitions/service-bot"